[language-server.clangd]
command = "/usr/bin/clangd"
args = ["--pretty", "--background-index", "-j=2", "--clang-tidy", "--clang-tidy-checks=performance-*,bugprone-*", "--all-scopes-completion", "--completion-style=detailed", "--header-insertion=iwyu", "--pch-storage=disk"]

[[language]]
name = "c"
language-servers = ["clangd"]
auto-format = false
